services:
  - type: web
    name: qx-auto-trader
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --worker-class uvicorn.workers.UvicornWorker
